### PR TITLE
use new CRUD page object

### LINKED ISSUE #260: UI tests failing
`Notice: Undefined property: Page\TextEditorPage::$newFileFolderButtonXpath in /var/www/owncloud/apps/files_texteditor/tests/acceptance/features/lib/TextEditorPage.php line 102`

### PR DESCRIPTION
**Pull request by individual-it**
use the new CRUD object to find the "+" button to create a new file
depends on https://github.com/owncloud/core/pull/33510 to be in the QA tarball

fixes #260

### CODE REVIEW

File: tests/acceptance/features/lib/TextEditorPage.php [hunk 1]
```diff
@@ -98,8 +98,7 @@ public function createTextFile(
 		$name = null,
 		$useDefaultFileExtension = false
 	) {
-		$newFileFolderButton
-			= $this->find("xpath", $this->newFileFolderButtonXpath);
+		$newFileFolderButton = $this->filesPageCRUDFunctions->findNewFileFolderButton();
 
 		if ($newFileFolderButton === null) {
```
Comment (phil-davis) [inline tests/acceptance/features/lib/TextEditorPage.php]: ``findNewFileFolderButton()`` will already have thrown an exception if this is null
``if`` block can be deleted

File: tests/acceptance/features/lib/TextEditorPage.php [hunk 2]
```diff
@@ -111,12 +110,6 @@ public function createTextFile(
 
 		$newTextFileButton = $this->find("xpath", $this->newTextFileButtonXpath);
 
-		if ($newTextFileButton === null) {
```
Comment (phil-davis) [inline tests/acceptance/features/lib/TextEditorPage.php]: IMO this ``if`` block needs to stay.

**Comment by individual-it** [comment]
stupid me, deleted the wrong if block
