### PR TITLE
package vendor/firebase/php-jwt

### LINKED ISSUE #388: [QA] dependency firebase/php-jwt is not packaged
Seen with files_texteditor-2.5.0

Since 2.5.0 we `use Firebase\JWT\JWT`, but this depenedency is not shipped with  files_texteditor. Instead, it mostly works, as files_external has the same dependency and is loaded earlier.
However, there are cases, where this does not seem to work: see https://central.owncloud.org/t/owncloud-10-after-text-editor-upgrade-to-version-2-50-unable-to-read-or-edit-text-files/41670

* Install files_texteditor-2.5.0
* `occ app:dis files_external`  # loads firebase/php-jwt normally.
* `occ app:dis wopi`   # also has a copy
* Try edit a text file with files_texteditor.
* The empty textedito window does not finish loading. An error is logged. BAD
```

Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'Firebase\\\\JWT\\\\JWT' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps-external\\\/files_texteditor\\\/controller\\\/filehandlingcontroller.php(400):
```

Workaround:
* `occ app:enable files_external`

### PR DESCRIPTION
**Pull request by jnweiger**
It does not seem safe to rely on vendor/firebase/php-jwt from files_external or elsewhere.
Seems we should package and use our own copy.

Fixes #388

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIActivity-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_texteditor/1989/14

**Review by pako81 — APPROVED** [review]

File: controller/filehandlingcontroller.php [hunk 1]
```diff
@@ -44,6 +44,8 @@
 
 use Firebase\JWT\JWT;
 
+require_once __DIR__ . '/../vendor/autoload.php';
```
Comment (phil-davis) [inline controller/filehandlingcontroller.php:47]: https://drone.owncloud.com/owncloud/files_texteditor/1989/7/5
```
[PHP Warning:  Uncaught require_once(/var/www/owncloud/server/apps/files_texteditor/controller/../vendor/autoload.php): failed to open stream: No such file or directory
```

**Review by phil-davis — APPROVED** [review]

**Comment by pako81** [comment]
merge?
