### PR TITLE
Display the error message when one was given

### LINKED ISSUE #126: Error not displayed correctly
If a exception occurs while loading a file we don't display a error message, instead we see a spinner forever. The texteditor in oC8.1 showed a popup with a error message.

Internally the error handling is the same, compare
https://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L112
and
https://github.com/owncloud/files_texteditor/blob/stable8.1/controller/filehandlingcontroller.php#L106

But for some reasons the response is no longer handled correctly on master.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #126 

@schiesbn @tomneedham 

might be worth backporting

### CODE REVIEW

File: controller/filehandlingcontroller.php [hunk 1]
```diff
@@ -143,7 +146,15 @@ public function save($path, $filecontents, $mtime) {
 				// File same as when opened, save file
 				if($this->view->isUpdatable($path)) {
 					$filecontents = iconv(mb_detect_encoding($filecontents), "UTF-8", $filecontents);
-					$this->view->file_put_contents($path, $filecontents);
+					try {
+						$this->view->file_put_contents($path, $filecontents);
+					} catch (LockedException $e) {
+						return new DataResponse(['message' => $e->getMessage()], Http::STATUS_BAD_REQUEST);
```
Comment (LukasReschke) [inline controller/filehandlingcontroller.php]: Sure that this is no regression of https://github.com/owncloud/files_texteditor/pull/96?

Comment (nickvergessen) [inline controller/filehandlingcontroller.php]: yes, load is fine, but save has issues....

Comment (nickvergessen) [inline controller/filehandlingcontroller.php]: Oh well, you intentionally kill all info. For locking this is quite bad. It failed to save for me just to make me realise, that I had a stray lock on the file....

well we should at least catch the exception and return an error string. But yeah maybe  kill the original one and use a custom text...

but e.g. for the firewall errors (`ForbiddenException`) it would be useful to display the error, so people know saving failed because of that.

Comment (nickvergessen) [inline controller/filehandlingcontroller.php]: adjusted

**Comment by nickvergessen** [comment]
Also added unit tests now

**Comment by tomneedham** [comment]
:+1: but do you know what is up with the failures in travis?

**Comment by nickvergessen** [comment]
Okay, the problem is:
1. travis broke phpunit on php7 atm
2. your app tries to be compatible with oC 8 to 9 on the same branch, which just doesn't work anymore. We want to be able to identify exceptions which don't exist in older ownCloud versions.

**Comment by nickvergessen** [comment]
But since we have stable8* branches for that, I think removing that is the correct approach

**Comment by PVince81** [comment]
> removing that

Removing what ?

**Comment by nickvergessen** [comment]
The tests against stable8* with teh master app, see https://github.com/owncloud/files_texteditor/issues/154

**Comment by PVince81** [comment]
:+1:

Merge or wait for the travis PR ?
